## Pandas :
#### Pandas is open source ,BSD Licensing library providing high performance , easy to use data 
#### structures and data analysis tools for the Python Programming Language 

In [23]:
# Step to import pandas 
import pandas as pd 
import numpy  as np 

In [ ]:
# Dataframe  
# A 2D data structure in Pandas with labeled axes 
# (rows and columns) that can hold different data types (integer, float, string, etc.) in each column.
df = pd.DataFrame(np.arange(40,90).reshape(10,5),
index=['row1','row2','row3','row4','row5','row6','row7','row8','row9','row10'],
columns=['marks1','marks2','marks3','marks4','marks5'])

df.head()
df.tail()

In [30]:
print(df)

       marks1  marks2  marks3  marks4  marks5
row1       40      41      42      43      44
row2       45      46      47      48      49
row3       50      51      52      53      54
row4       55      56      57      58      59
row5       60      61      62      63      64
row6       65      66      67      68      69
row7       70      71      72      73      74
row8       75      76      77      78      79
row9       80      81      82      83      84
row10      85      86      87      88      89


In [35]:
df.to_csv('Panda_text')

In [42]:
# Accessing the elements 
# 1 . loc
# 2 . iloc
df.loc['row1']

marks1    40
marks2    41
marks3    42
marks4    43
marks5    44
Name: row1, dtype: int64

In [43]:
df.loc['row2']

marks1    45
marks2    46
marks3    47
marks4    48
marks5    49
Name: row2, dtype: int64

In [44]:
df.loc['row3']

marks1    50
marks2    51
marks3    52
marks4    53
marks5    54
Name: row3, dtype: int64

In [45]:
df.loc['row4']

marks1    55
marks2    56
marks3    57
marks4    58
marks5    59
Name: row4, dtype: int64

In [48]:
df.iloc[:,:]

marks1  marks2  marks3  marks4  marks5
row1       40      41      42      43      44
row2       45      46      47      48      49
row3       50      51      52      53      54
row4       55      56      57      58      59
row5       60      61      62      63      64
row6       65      66      67      68      69
row7       70      71      72      73      74
row8       75      76      77      78      79
row9       80      81      82      83      84
row10      85      86      87      88      89

In [50]:
#Here we want to retrieve the rows between 4 and 6 and columns between 1 and 3.....
df.iloc[4:7,1:3]

marks2  marks3
row5      61      62
row6      66      67
row7      71      72

In [52]:
# Here we want to retrieve the rows between 3 and 4 , columns between 1 and 5.
df.iloc[3:4,1:5]


marks2  marks3  marks4  marks5
row4      56      57      58      59

In [54]:
type(df.loc['row4'])

pandas.core.series.Series

In [56]:
type(df.iloc[0:5,2:5])

pandas.core.frame.DataFrame

In [64]:
df.iloc[2:6,3:]

marks4  marks5
row3      53      54
row4      58      59
row5      63      64
row6      68      69

In [69]:
df.iloc[2:5,0:4].values

array([[50, 51, 52, 53],
       [55, 56, 57, 58],
       [60, 61, 62, 63]])

In [72]:
df.iloc[1:5,2:5].values.shape

(4, 3)

In [76]:
df['marks2'].value_counts()

marks2
41    1
46    1
51    1
56    1
61    1
66    1
71    1
76    1
81    1
86    1
Name: count, dtype: int64

In [80]:
df.isnull().sum()

marks1    0
marks2    0
marks3    0
marks4    0
marks5    0
dtype: int64

In [83]:
df['marks1'].unique()

array([40, 45, 50, 55, 60, 65, 70, 75, 80, 85])

In [84]:
df['marks4'].unique()

array([43, 48, 53, 58, 63, 68, 73, 78, 83, 88])

In [86]:
df['marks5'].unique()

array([44, 49, 54, 59, 64, 69, 74, 79, 84, 89])