## Numpy Practise 

In [3]:
import numpy as np 
import pandas as pd
from io import StringIO , BytesIO

In [4]:
list1 = np.array([1,2,3])
list2 = np.array([4,5,6])
list3 = np.array([7,8,9])
data = np.array([list1,list2,list3])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
data=np.arange(10,45,step=2)
data

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44])

In [8]:
data = np.linspace (10,57,2).astype(float)
data

array([10., 57.])

In [9]:
data = np.full((4,7),7)
data

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [10]:
data = np.eye(4)
data

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
data = np.random.random((3,3))
data

array([[0.73592626, 0.08455085, 0.94885436],
       [0.26065111, 0.42606239, 0.719705  ],
       [0.41442641, 0.0958427 , 0.11902111]])

In [12]:
data = np.empty((4,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
data = np.arange(10,100,step=2)
data

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
data.shape

(45,)

In [15]:
len(data)

45

In [16]:
data.ndim

1

In [17]:
data = np.eye(4,4)
data

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
data.ndim

2

In [19]:
data.size

16

In [20]:
data.dtype

dtype('float64')

In [21]:
data.dtype.name

'float64'

In [22]:
data.astype(int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [23]:
# Data types :
np.int64

numpy.int64

In [24]:
np.float64

numpy.float64

In [31]:
np.bool

numpy.bool

In [34]:
np.arange(1,45,2.3)

array([ 1. ,  3.3,  5.6,  7.9, 10.2, 12.5, 14.8, 17.1, 19.4, 21.7, 24. ,
       26.3, 28.6, 30.9, 33.2, 35.5, 37.8, 40.1, 42.4, 44.7])

In [63]:
x = np.array(np.arange(2,100,2))
y = np.array(np.arange(1,50,1))

data = x-y
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [64]:
data = x+y
data

array([  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
        42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,
        81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117,
       120, 123, 126, 129, 132, 135, 138, 141, 144, 147])

In [65]:
data = x/y
data

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [66]:
data  = x*y
data

array([   2,    8,   18,   32,   50,   72,   98,  128,  162,  200,  242,
        288,  338,  392,  450,  512,  578,  648,  722,  800,  882,  968,
       1058, 1152, 1250, 1352, 1458, 1568, 1682, 1800, 1922, 2048, 2178,
       2312, 2450, 2592, 2738, 2888, 3042, 3200, 3362, 3528, 3698, 3872,
       4050, 4232, 4418, 4608, 4802])

In [67]:
data = x%y
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [68]:
data = x+(y/x)*x
data

array([  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.,  33.,
        36.,  39.,  42.,  45.,  48.,  51.,  54.,  57.,  60.,  63.,  66.,
        69.,  72.,  75.,  78.,  81.,  84.,  87.,  90.,  93.,  96.,  99.,
       102., 105., 108., 111., 114., 117., 120., 123., 126., 129., 132.,
       135., 138., 141., 144., 147.])

In [71]:
data = np.pow(x,2)+np.pow(y,2)
data

array([    5,    20,    45,    80,   125,   180,   245,   320,   405,
         500,   605,   720,   845,   980,  1125,  1280,  1445,  1620,
        1805,  2000,  2205,  2420,  2645,  2880,  3125,  3380,  3645,
        3920,  4205,  4500,  4805,  5120,  5445,  5780,  6125,  6480,
        6845,  7220,  7605,  8000,  8405,  8820,  9245,  9680, 10125,
       10580, 11045, 11520, 12005])

In [75]:
data=np.pow((x+y),2)+np.pow(2,(x+y))
data

array([                  17,                  100,                  593,
                       4240,                32993,               262468,
                    2097593,             16777792,            134218457,
                 1073742724,           8589935681,          68719478032,
               549755815409,        4398046512868,       35184372090857,
            281474976712960,     2251799813687849,    18014398509484900,
         144115188075859121,  1152921504606850576, -9223372036854771839,
                       4356,                 4761,                 5184,
                       5625,                 6084,                 6561,
                       7056,                 7569,                 8100,
                       8649,                 9216,                 9801,
                      10404,                11025,                11664,
                      12321,                12996,                13689,
                      14400,                15129, 

In [80]:
np.exp(x+y)

array([2.00855369e+01, 4.03428793e+02, 8.10308393e+03, 1.62754791e+05,
       3.26901737e+06, 6.56599691e+07, 1.31881573e+09, 2.64891221e+10,
       5.32048241e+11, 1.06864746e+13, 2.14643580e+14, 4.31123155e+15,
       8.65934004e+16, 1.73927494e+18, 3.49342711e+19, 7.01673591e+20,
       1.40934908e+22, 2.83075330e+23, 5.68572000e+24, 1.14200739e+26,
       2.29378316e+27, 4.60718663e+28, 9.25378173e+29, 1.85867175e+31,
       3.73324200e+32, 7.49841700e+33, 1.50609731e+35, 3.02507732e+36,
       6.07603023e+37, 1.22040329e+39, 2.45124554e+40, 4.92345829e+41,
       9.88903032e+42, 1.98626484e+44, 3.98951957e+45, 8.01316426e+46,
       1.60948707e+48, 3.23274119e+49, 6.49313426e+50, 1.30418088e+52,
       2.61951732e+53, 5.26144118e+54, 1.05678871e+56, 2.12261687e+57,
       4.26338995e+58, 8.56324762e+59, 1.71997426e+61, 3.45466066e+62,
       6.93887142e+63])

In [83]:
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [85]:
np.log(x)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509,
       2.48490665, 2.63905733, 2.77258872, 2.89037176, 2.99573227,
       3.09104245, 3.17805383, 3.25809654, 3.33220451, 3.40119738,
       3.4657359 , 3.52636052, 3.58351894, 3.63758616, 3.68887945,
       3.73766962, 3.78418963, 3.8286414 , 3.87120101, 3.91202301,
       3.95124372, 3.98898405, 4.02535169, 4.06044301, 4.09434456,
       4.12713439, 4.15888308, 4.18965474, 4.21950771, 4.24849524,
       4.27666612, 4.30406509, 4.33073334, 4.35670883, 4.38202663,
       4.40671925, 4.4308168 , 4.4543473 , 4.47733681, 4.49980967,
       4.52178858, 4.54329478, 4.56434819, 4.58496748])

In [86]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [87]:
np.log(y)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ])

In [90]:
list1 = [np.log(y)]
list1
list2 = [np.log(x)]
list2

[array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509,
        2.48490665, 2.63905733, 2.77258872, 2.89037176, 2.99573227,
        3.09104245, 3.17805383, 3.25809654, 3.33220451, 3.40119738,
        3.4657359 , 3.52636052, 3.58351894, 3.63758616, 3.68887945,
        3.73766962, 3.78418963, 3.8286414 , 3.87120101, 3.91202301,
        3.95124372, 3.98898405, 4.02535169, 4.06044301, 4.09434456,
        4.12713439, 4.15888308, 4.18965474, 4.21950771, 4.24849524,
        4.27666612, 4.30406509, 4.33073334, 4.35670883, 4.38202663,
        4.40671925, 4.4308168 , 4.4543473 , 4.47733681, 4.49980967,
        4.52178858, 4.54329478, 4.56434819, 4.58496748])]

In [98]:
data= np.array([list1,list2])
data

array([[[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
         1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
         2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
         2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
         3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
         3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
         3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
         3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
         3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
         3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ]],

       [[0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509,
         2.48490665, 2.63905733, 2.77258872, 2.89037176, 2.99573227,
         3.09104245, 3.17805383, 3.25809654, 3.33220451, 3.40119738,
         3.4657359 , 3.52636052, 3.58351894, 3.63758616, 3.68887945,
         3.73766962, 3.78418963, 3.8286414 

In [103]:
np.dot

<function dot at 0x000002D62D940770>

In [106]:
len(list1)==len(list2)

True

In [113]:
np.array_equal(x,y)

False