## Numpy Practise 

In [1]:
import numpy as np 
import pandas as pd
from io import StringIO , BytesIO

In [8]:
list1 = np.array([1,2,3])
list2 = np.array([4,5,6])
list3 = np.array([7,8,9])
data = np.array([list1,list2,list3])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
data=np.arange(10,45,step=2)
data

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44])

In [22]:
data = np.linspace (10,57,2).astype(float)
data

array([10., 57.])

In [25]:
data = np.full((4,7),7)
data

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [28]:
data = np.eye(4)
data

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
data = np.random.random((3,3))
data

array([[0.37197498, 0.71815483, 0.37387536],
       [0.78249755, 0.84798894, 0.66606309],
       [0.15922905, 0.20002513, 0.03193137]])

In [37]:
data = np.empty((4,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
data = np.arange(10,100,step=2)
data

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [44]:
data.shape

(45,)

In [48]:
len(data)

45

In [49]:
data.ndim

1

In [51]:
data = np.eye(4,4)
data

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
data.ndim

2

In [53]:
data.size

16

In [54]:
data.dtype

dtype('float64')

In [55]:
data.dtype.name

'float64'

In [56]:
data.astype(int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [58]:
# Data types :
np.int64

numpy.int64

In [59]:
np.float64

numpy.float64

In [ ]:
np,