In [14]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv('C:\mercedesbenz.csv')

In [28]:
df.head()

ID           y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  \
0   1  100.858650  az  v   n  f  d  t  a  w  ...     0     0     0     1   
1   2   96.851370   t  b  ai  a  d  b  g  y  ...     0     0     1     0   
2   3   96.221504  az  v  as  f  d  a  j  j  ...     0     0     0     1   
3   4   96.831085  az  l   n  f  d  z  l  n  ...     0     0     0     1   
4   5  100.977974   w  s  as  c  d  y  i  m  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 378 columns]

In [39]:
#This funstion shows all the details about the file whether how many of elements of 
# different data types are in this file 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [40]:
# df.describe() : this function provide us the most details about the 
# file (count,mean,std,min,25% percentile,50% percentile,75% percentile,max) as default ..
df.describe()

ID            y          X10          X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean   4211.039202    97.071149     0.019007     0.000238     0.074364   
std    2423.078926     4.752607     0.136565     0.015414     0.262394   
min       1.000000    86.844470     0.000000     0.000000     0.000000   
25%    2115.000000    93.604380     0.000000     0.000000     0.000000   
50%    4202.000000    96.050650     0.000000     0.000000     0.000000   
75%    6310.000000    99.503060     0.000000     0.000000     0.000000   
max    8416.000000   125.425480     1.000000     1.000000     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.061060     0.427893     0.000713     0.002613     0.008791  ...   
std       0.239468     0.494832     0.026691     0.051061     0.093357  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.325968     0.049656     0.311951     0.019244     0.011879   
std       0.468791     0.217258     0.463345     0.137399     0.108356   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.008791     0.000475     0.000713     0.001663  
std       0.089524     0.093357     0.021796     0.026691     0.040752  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [45]:
# Get the unique category counts ...
df['ID'].unique()

array([   1,    2,    3, ..., 8413, 8414, 8416], shape=(4209,))

In [46]:
df['X14'].unique()

array([0, 1])

In [47]:
df['X16'].unique()

array([0, 1])

In [48]:
df['y'].unique()

array([100.85865 ,  96.85137 ,  96.221504, ...,  91.628654, 102.32196 ,
        93.3977  ], shape=(3663,))

In [51]:
# Retrieve the json file in the form of csv ..
test_df = pd.read_csv('C:\mercedesbenz.csv',sep=',')

In [52]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [53]:
test_df.describe()

ID            y          X10          X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean   4211.039202    97.071149     0.019007     0.000238     0.074364   
std    2423.078926     4.752607     0.136565     0.015414     0.262394   
min       1.000000    86.844470     0.000000     0.000000     0.000000   
25%    2115.000000    93.604380     0.000000     0.000000     0.000000   
50%    4202.000000    96.050650     0.000000     0.000000     0.000000   
75%    6310.000000    99.503060     0.000000     0.000000     0.000000   
max    8416.000000   125.425480     1.000000     1.000000     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.061060     0.427893     0.000713     0.002613     0.008791  ...   
std       0.239468     0.494832     0.026691     0.051061     0.093357  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.325968     0.049656     0.311951     0.019244     0.011879   
std       0.468791     0.217258     0.463345     0.137399     0.108356   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.008791     0.000475     0.000713     0.001663  
std       0.089524     0.093357     0.021796     0.026691     0.040752  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [54]:
test_df.head()

ID           y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  \
0   1  100.858650  az  v   n  f  d  t  a  w  ...     0     0     0     1   
1   2   96.851370   t  b  ai  a  d  b  g  y  ...     0     0     1     0   
2   3   96.221504  az  v  as  f  d  a  j  j  ...     0     0     0     1   
3   4   96.831085  az  l   n  f  d  z  l  n  ...     0     0     0     1   
4   5  100.977974   w  s  as  c  d  y  i  m  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 378 columns]

In [57]:
# values_counts() function : It gives the unique category counts ...
df['X0'].value_counts()

X0
ak    432
y     348
z     335
x     302
ay    299
t     293
o     246
f     213
w     198
j     171
n     167
aj    162
az    161
s     116
ap    108
al     88
h      64
d      61
e      48
v      40
ai     38
af     34
m      34
am     28
i      25
at     21
u      20
ba     19
a      18
b      13
ad     12
k      12
aq     11
aw     11
r      10
ax      8
as      6
bc      6
l       6
c       6
ao      5
au      5
g       3
ag      1
av      1
an      1
ae      1
p       1
bb      1
Name: count, dtype: int64

In [63]:
# Find those records havingy>100
df[test_df['y']>100]

ID           y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  \
0        1  100.858650  az  v   n  f  d   t  a  w  ...     0     0     0   
4        5  100.977974   w  s  as  c  d   y  i  m  ...     1     0     0   
6       10  100.839250   x  b  ae  d  d   x  d  y  ...     0     0     0   
8       12  105.236305  ap  l   s  c  d   h  j  n  ...     0     0     0   
10      15  105.229110  ap  l   s  c  d   g  d  n  ...     0     0     0   
...    ...         ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   
4196  8396  103.758644  aj  l  as  f  d  aa  j  e  ...     0     0     0   
4198  8400  100.674850  ak  e  as  a  d  aa  j  a  ...     0     0     1   
4203  8409  100.274990   j  o   t  d  d  aa  j  l  ...     0     1     0   
4204  8410  105.965890  aj  h  as  f  d  aa  j  e  ...     0     0     0   
4207  8414  102.321960  ak  v  as  a  d  aa  c  q  ...     0     0     1   

      X378  X379  X380  X382  X383  X384  X385  
0        1     0     0     0     0     0     0  
4        0     0     0     0     0     0     0  
6        0     0     1     0     0     0     0  
8        0     0     0     0     0     0     0  
10       0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...  
4196     0     0     0     0     0     0     0  
4198     0     0     0     0     0     0     0  
4203     0     0     0     0     0     0     0  
4204     0     0     0     0     0     0     0  
4207     0     0     0     0     0     0     0  

[974 rows x 378 columns]

In [65]:
df[df['y']<90]

ID         y X0  X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
52      91  88.94691  t  aa   m  c  d   j  g  b  ...     1     0     0     0   
59      99  88.58743  t  aa  as  c  d   j  d  b  ...     1     0     0     0   
124    236  89.97440  t  aa  ay  c  d   j  g  n  ...     1     0     0     0   
127    243  88.94691  t  aa   m  c  d   j  k  b  ...     1     0     0     0   
134    251  89.97440  t  aa  ay  c  d   j  g  n  ...     1     0     0     0   
...    ...       ... ..  ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
3375  6765  88.68628  t  aa   m  g  d   s  g  a  ...     1     0     0     0   
3664  7316  87.38450  s  aa   m  c  d   v  j  c  ...     1     0     0     0   
4125  8258  87.57741  n   l  as  f  d  aa  a  h  ...     0     0     0     0   
4131  8268  88.13702  n   l  as  f  d  aa  l  d  ...     0     0     0     0   
4201  8407  89.17157  o   l  as  f  d  aa  d  a  ...     0     0     0     0   

      X379  X380  X382  X383  X384  X385  
52       0     0     0     0     0     0  
59       0     0     0     0     0     0  
124      0     0     0     0     0     0  
127      0     0     0     0     0     0  
134      0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
3375     0     0     0     0     0     0  
3664     0     0     0     0     0     0  
4125     0     0     0     0     0     0  
4131     0     0     0     0     0     0  
4201     0     0     0     0     0     0  

[81 rows x 378 columns]

In [74]:
df2 = df[df['y']<90]
df2.describe()
print(df2)

        ID         y X0  X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
52      91  88.94691  t  aa   m  c  d   j  g  b  ...     1     0     0     0   
59      99  88.58743  t  aa  as  c  d   j  d  b  ...     1     0     0     0   
124    236  89.97440  t  aa  ay  c  d   j  g  n  ...     1     0     0     0   
127    243  88.94691  t  aa   m  c  d   j  k  b  ...     1     0     0     0   
134    251  89.97440  t  aa  ay  c  d   j  g  n  ...     1     0     0     0   
...    ...       ... ..  ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
3375  6765  88.68628  t  aa   m  g  d   s  g  a  ...     1     0     0     0   
3664  7316  87.38450  s  aa   m  c  d   v  j  c  ...     1     0     0     0   
4125  8258  87.57741  n   l  as  f  d  aa  a  h  ...     0     0     0     0   
4131  8268  88.13702  n   l  as  f  d  aa  l  d  ...     0     0     0     0   
4201  8407  89.17157  o   l  as  f  d  aa  d  a  ...     0     0     0     0   

      X379  X380  X382  X383  X384  X38

In [75]:
df.head()

ID           y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  \
0   1  100.858650  az  v   n  f  d  t  a  w  ...     0     0     0     1   
1   2   96.851370   t  b  ai  a  d  b  g  y  ...     0     0     1     0   
2   3   96.221504  az  v  as  f  d  a  j  j  ...     0     0     0     1   
3   4   96.831085  az  l   n  f  d  z  l  n  ...     0     0     0     1   
4   5  100.977974   w  s  as  c  d  y  i  m  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 378 columns]

In [76]:
df.tail()

ID           y  X0  X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  \
4204  8410  105.965890  aj   h  as  f  d  aa  j  e  ...     0     0     0   
4205  8411   93.769620   t  aa  ai  d  d  aa  j  y  ...     0     1     0   
4206  8413   91.628654   y   v  as  f  d  aa  d  w  ...     0     0     0   
4207  8414  102.321960  ak   v  as  a  d  aa  c  q  ...     0     0     1   
4208  8416   93.397700   t  aa  ai  c  d  aa  g  r  ...     1     0     0   

      X378  X379  X380  X382  X383  X384  X385  
4204     0     0     0     0     0     0     0  
4205     0     0     0     0     0     0     0  
4206     0     0     0     0     0     0     0  
4207     0     0     0     0     0     0     0  
4208     0     0     0     0     0     0     0  

[5 rows x 378 columns]

ID          y        X10   X11        X12   X13        X14  \
count    81.000000  81.000000  81.000000  81.0  81.000000  81.0  81.000000   
mean   2872.012346  89.135863   0.197531   0.0   0.012346   0.0   0.395062   
std    2014.319851   0.711049   0.400617   0.0   0.111111   0.0   0.491910   
min      91.000000  86.844470   0.000000   0.0   0.000000   0.0   0.000000   
25%    1461.000000  88.895940   0.000000   0.0   0.000000   0.0   0.000000   
50%    2434.000000  89.171570   0.000000   0.0   0.000000   0.0   0.000000   
75%    3938.000000  89.681130   0.000000   0.0   0.000000   0.0   1.000000   
max    8407.000000  89.988594   1.000000   0.0   1.000000   0.0   1.000000   

        X15   X16   X17  ...       X375  X376       X377  X378  X379  X380  \
count  81.0  81.0  81.0  ...  81.000000  81.0  81.000000  81.0  81.0  81.0   
mean    0.0   0.0   0.0  ...   0.666667   0.0   0.049383   0.0   0.0   0.0   
std     0.0   0.0   0.0  ...   0.474342   0.0   0.218016   0.0   0.0   0.0   
min     0.0   0.0   0.0  ...   0.000000   0.0   0.000000   0.0   0.0   0.0   
25%     0.0   0.0   0.0  ...   0.000000   0.0   0.000000   0.0   0.0   0.0   
50%     0.0   0.0   0.0  ...   1.000000   0.0   0.000000   0.0   0.0   0.0   
75%     0.0   0.0   0.0  ...   1.000000   0.0   0.000000   0.0   0.0   0.0   
max     0.0   0.0   0.0  ...   1.000000   0.0   1.000000   0.0   0.0   0.0   

       X382  X383  X384  X385  
count  81.0  81.0  81.0  81.0  
mean    0.0   0.0   0.0   0.0  
std     0.0   0.0   0.0   0.0  
min     0.0   0.0   0.0   0.0  
25%     0.0   0.0   0.0   0.0  
50%     0.0   0.0   0.0   0.0  
75%     0.0   0.0   0.0   0.0  
max     0.0   0.0   0.0   0.0  

[8 rows x 370 columns]