# Numpy

In [1]:
# Numpy 
# Numpy is general purpose array processing package . It provides a high performance multidimensional 
# array object , and tools for working with these arrays . It is the fundamental package for scientific computing with python 

In [2]:
# Array is the collection of elements having the same data types , It is the main difference between the array and list 
# while python can contain the values corressponding to different data types , arrays in python can only contains values 
# corressponding to same data type 

In [5]:
mylst = (1,2,4,"aayush",5,"aman")
print(mylst)

(1, 2, 4, 'aayush', 5, 'aman')


In [10]:
myarray = {12,12,13,34,56,"aayush"}    #set doenot contain the duplicate elements rather list do 
print(myarray)
print(type(myarray))

{34, 'aayush', 56, 12, 13}
<class 'set'>


In [25]:
mylist = [43,54,56,23,78,15,98]
print(type(mylist))
1
myset = {54,56,43,76,78,'aayush','pateriya'}
print(type(myset))

mydictionary={'name':'aayush'}
print(mydictionary)
print(type(mydictionary))
print(mydictionary['name']) 

<class 'list'>
<class 'set'>
{'name': 'aayush'}
<class 'dict'>
aayush


In [26]:
mylst = ['aayush',1,'pateriya',2,'Disha',3,'pateriya']
print(mylst)

['aayush', 1, 'pateriya', 2, 'Disha', 3, 'pateriya']


In [28]:
import numpy as np
arr = np.array(mylst)

In [29]:
print(arr)

['aayush' '1' 'pateriya' '2' 'Disha' '3' 'pateriya']


In [30]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
 # Creation of the multinested array
lst1 = [1,'Aayush','Pateriya']
lst2 = ['Mayank',65,'Agarwal']
lst3 = ['Chote',54,'Ahirwar']
lst4 = ['Aarohi',67,67]

arr = np.array([lst1,lst2,lst3,lst4])
print(arr)

[['1' 'Aayush' 'Pateriya']
 ['Mayank' '65' 'Agarwal']
 ['Chote' '54' 'Ahirwar']
 ['Aarohi' '67' '67']]


In [31]:
arr.shape

(7,)

In [7]:
arr.shape #This shows that there is 3 rows and 3 columns .....

(4, 3)

In [8]:
# Here we reshape the array .
arr.reshape(3,4)

array([['1', 'Aayush', 'Pateriya', 'Mayank'],
       ['65', 'Agarwal', 'Chote', '54'],
       ['Ahirwar', 'Aarohi', '67', '67']], dtype='<U21')

In [9]:
arr.shape

(4, 3)

In [10]:
lst5 = [54,'Bhupinder','Jogi']
print(lst5)

[54, 'Bhupinder', 'Jogi']


In [12]:
arr[3]

array(['Aarohi', '67', '67'], dtype='<U21')

In [11]:
## Indexing
# Accessing the array elements 
arr

array([['1', 'Aayush', 'Pateriya'],
       ['Mayank', '65', 'Agarwal'],
       ['Chote', '54', 'Ahirwar'],
       ['Aarohi', '67', '67']], dtype='<U21')

In [13]:
arr[1]

array(['Mayank', '65', 'Agarwal'], dtype='<U21')

In [14]:
print(arr)

[['1' 'Aayush' 'Pateriya']
 ['Mayank' '65' 'Agarwal']
 ['Chote' '54' 'Ahirwar']
 ['Aarohi' '67' '67']]


In [15]:
arr.reshape(6,2)

array([['1', 'Aayush'],
       ['Pateriya', 'Mayank'],
       ['65', 'Agarwal'],
       ['Chote', '54'],
       ['Ahirwar', 'Aarohi'],
       ['67', '67']], dtype='<U21')

In [16]:
print(arr)

[['1' 'Aayush' 'Pateriya']
 ['Mayank' '65' 'Agarwal']
 ['Chote' '54' 'Ahirwar']
 ['Aarohi' '67' '67']]


In [17]:
print(arr.reshape(6,2))

[['1' 'Aayush']
 ['Pateriya' 'Mayank']
 ['65' 'Agarwal']
 ['Chote' '54']
 ['Ahirwar' 'Aarohi']
 ['67' '67']]


In [18]:
print(arr)

[['1' 'Aayush' 'Pateriya']
 ['Mayank' '65' 'Agarwal']
 ['Chote' '54' 'Ahirwar']
 ['Aarohi' '67' '67']]


In [19]:
print(arr[0:2,2])

['Pateriya' 'Agarwal']


In [20]:
print(arr)
print(arr[1:2,2])
print(arr[2:3])

[['1' 'Aayush' 'Pateriya']
 ['Mayank' '65' 'Agarwal']
 ['Chote' '54' 'Ahirwar']
 ['Aarohi' '67' '67']]
['Agarwal']
[['Chote' '54' 'Ahirwar']]


In [21]:
print(arr[0:4,2])

['Pateriya' 'Agarwal' 'Ahirwar' '67']


In [34]:
import numpy as np

l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [11,12,13,14,15]
l4 = [16,17,18,19,20]
arr = np.array([l1,l2,l3,l4])
print(arr)
print(arr.shape)
print(arr.reshape(10,2))
print(arr.reshape(20,1))

print(arr[0:4,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]
[ 4  9 14 19]


In [38]:
print(arr[1:5,4])

[10 15 20]


In [60]:
np.arange(0,20,step=2)
print (np.arange(0,20,step=2*1/2).astype(float))
print("---------------------------------")
print(np.arange(0,20,step=2+2).astype(np.float32))
print("---------------------------------")
np.arange(0,20,step=2*3/4).astype(np.float64)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
---------------------------------
[ 0.  4.  8. 12. 16.]
---------------------------------


array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])

## Array Creation Functions 

In [62]:
 np.array()          : Create array from list or tuple np.array([1,2,3])
 np.arange()         : Create sequence with step np.arange(0,10,2)
 np.linspace()       : Evenly spaced values np.linspace(0,1,5)
 np.zeros()          : All zeros np.zeros((3,3))
 np.ones()           : All ones np.ones((2,2))
 np.eye()            : Identity matrix np.eye(3)
 np.full()           : Constant array np.full((2,2),7)
 np.random.rand()    :Random (0–1) np.random.rand(3,2)
 np.random.randint() : Random integers np.random.randint(1,10,(3,3))
 np.empty()          :Uninitialized array np.empty((3,3)

In [8]:
import numpy as np
list1 = [2,4,6,8]
list2 =[4,8,12,16]
list3 = [6,12,18,24]
list4 = [8,16,24,32]
arr = np.array([list1,list2,list3,list4])
print(arr)

[[ 2  4  6  8]
 [ 4  8 12 16]
 [ 6 12 18 24]
 [ 8 16 24 32]]


In [9]:
# Function to check the data type of array 
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
# Function to reshape the array 
arr.reshape(8,2) # here there are 8 rows and 2 columns
print("--------------------")
arr.reshape(4,4)  #Here there are 4 rows and 4 columns 

--------------------


array([[ 2,  4,  6,  8],
       [ 4,  8, 12, 16],
       [ 6, 12, 18, 24],
       [ 8, 16, 24, 32]])

In [11]:
# Function to arange the array 
# np.arange([start,] stop[, step,], dtype=None)
np.arange(1,32,step=2).reshape(4,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [12]:
np.arange(4,56,4)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52])

In [13]:
np.arange(2,60,1.5)

array([ 2. ,  3.5,  5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. , 15.5, 17. ,
       18.5, 20. , 21.5, 23. , 24.5, 26. , 27.5, 29. , 30.5, 32. , 33.5,
       35. , 36.5, 38. , 39.5, 41. , 42.5, 44. , 45.5, 47. , 48.5, 50. ,
       51.5, 53. , 54.5, 56. , 57.5, 59. ])

In [14]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
np.linspace(1,16,50)

array([ 1.        ,  1.30612245,  1.6122449 ,  1.91836735,  2.2244898 ,
        2.53061224,  2.83673469,  3.14285714,  3.44897959,  3.75510204,
        4.06122449,  4.36734694,  4.67346939,  4.97959184,  5.28571429,
        5.59183673,  5.89795918,  6.20408163,  6.51020408,  6.81632653,
        7.12244898,  7.42857143,  7.73469388,  8.04081633,  8.34693878,
        8.65306122,  8.95918367,  9.26530612,  9.57142857,  9.87755102,
       10.18367347, 10.48979592, 10.79591837, 11.10204082, 11.40816327,
       11.71428571, 12.02040816, 12.32653061, 12.63265306, 12.93877551,
       13.24489796, 13.55102041, 13.85714286, 14.16326531, 14.46938776,
       14.7755102 , 15.08163265, 15.3877551 , 15.69387755, 16.        ])

In [15]:
# Linspace Function 2 
np.linspace(2,16,50)

array([ 2.        ,  2.28571429,  2.57142857,  2.85714286,  3.14285714,
        3.42857143,  3.71428571,  4.        ,  4.28571429,  4.57142857,
        4.85714286,  5.14285714,  5.42857143,  5.71428571,  6.        ,
        6.28571429,  6.57142857,  6.85714286,  7.14285714,  7.42857143,
        7.71428571,  8.        ,  8.28571429,  8.57142857,  8.85714286,
        9.14285714,  9.42857143,  9.71428571, 10.        , 10.28571429,
       10.57142857, 10.85714286, 11.14285714, 11.42857143, 11.71428571,
       12.        , 12.28571429, 12.57142857, 12.85714286, 13.14285714,
       13.42857143, 13.71428571, 14.        , 14.28571429, 14.57142857,
       14.85714286, 15.14285714, 15.42857143, 15.71428571, 16.        ])

In [16]:
np.linspace(21,23,43)

array([21.        , 21.04761905, 21.0952381 , 21.14285714, 21.19047619,
       21.23809524, 21.28571429, 21.33333333, 21.38095238, 21.42857143,
       21.47619048, 21.52380952, 21.57142857, 21.61904762, 21.66666667,
       21.71428571, 21.76190476, 21.80952381, 21.85714286, 21.9047619 ,
       21.95238095, 22.        , 22.04761905, 22.0952381 , 22.14285714,
       22.19047619, 22.23809524, 22.28571429, 22.33333333, 22.38095238,
       22.42857143, 22.47619048, 22.52380952, 22.57142857, 22.61904762,
       22.66666667, 22.71428571, 22.76190476, 22.80952381, 22.85714286,
       22.9047619 , 22.95238095, 23.        ])

##### Copy function() and BroadCasting() :

In [17]:
# np.copy() is used to create a complete copy of a NumPy array.
# It creates a new array in memory, so that changes in the new array do not affect the original array.

In [18]:
list1 = ['Maths','English','Physics','Chemistry','Computer Application']
list2 = [100,26,38,49]
list3 = [65,78,45,65]
list4 = [87,78,89,98]
list5 = [54,87,34,90]
arr = np.array([list2,list3,list4,list5])
print(arr)

[[100  26  38  49]
 [ 65  78  45  65]
 [ 87  78  89  98]
 [ 54  87  34  90]]


In [19]:
list2[2] = 68
print(list2)

[100, 26, 68, 49]


In [20]:
arr[3:]=80
print(arr)

[[100  26  38  49]
 [ 65  78  45  65]
 [ 87  78  89  98]
 [ 80  80  80  80]]


In [21]:
arr1 = arr.copy()
print(arr1)

[[100  26  38  49]
 [ 65  78  45  65]
 [ 87  78  89  98]
 [ 80  80  80  80]]


In [23]:
arr1.reshape(2,8)

array([[100,  26,  38,  49,  65,  78,  45,  65],
       [ 87,  78,  89,  98,  80,  80,  80,  80]])

In [27]:
arr1.reshape(1,16)

array([[100,  26,  38,  49,  65,  78,  45,  65,  87,  78,  89,  98,  80,
         80,  80,  80]])

In [44]:
# Zeroes Function() : Zeroes function is used to create  a new array  of given shape  filled  entirely with 0s
# numpy.zeros(shape, dtype=float, order='C')
arr2 = np.zeros(5)


TypeError: Cannot interpret '4' as a data type