In [34]:
import numpy as np
l1 = [11,22,33,44]
l2 = [55,66,77,88]
l3 = [99,110,121,132]
l4 = [143,154,165,176]
arr = np.array([l1,l2,l3,l4])
print(arr)

[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 110 121 132]
 [143 154 165 176]]


In [35]:
arr.reshape(8,2)

array([[ 11,  22],
       [ 33,  44],
       [ 55,  66],
       [ 77,  88],
       [ 99, 110],
       [121, 132],
       [143, 154],
       [165, 176]])

In [36]:
np.arange(11,176,step=4)

array([ 11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,  55,  59,
        63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103, 107, 111,
       115, 119, 123, 127, 131, 135, 139, 143, 147, 151, 155, 159, 163,
       167, 171, 175])

In [37]:
np.linspace(1,176,176).astype(float)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [38]:
np.ones(7,dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

In [39]:
np.ones((7,8),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [40]:
# Random distribution 
np.random.rand(4,4)

array([[0.82010391, 0.65696791, 0.36988104, 0.75740828],
       [0.03791008, 0.39998865, 0.20968816, 0.8591489 ],
       [0.24202125, 0.22088754, 0.78180277, 0.14733921],
       [0.40424044, 0.7106492 , 0.16188979, 0.25783164]])

In [51]:
np.random.rand(8,10)

array([[0.68109959, 0.52748027, 0.71270008, 0.45368379, 0.86818995,
        0.58529296, 0.12712963, 0.1519436 , 0.20539253, 0.69176033],
       [0.16551744, 0.7795652 , 0.7064633 , 0.05186539, 0.39311346,
        0.05717249, 0.14151713, 0.13385637, 0.61823275, 0.47303239],
       [0.76714263, 0.23087624, 0.81800954, 0.74184495, 0.16955448,
        0.76384249, 0.06203366, 0.51434684, 0.90164217, 0.93139224],
       [0.70974845, 0.73731283, 0.91878664, 0.1852044 , 0.68093901,
        0.50382806, 0.93765411, 0.76751725, 0.97603314, 0.79561153],
       [0.7650947 , 0.41522295, 0.13756483, 0.10393848, 0.88573083,
        0.50261078, 0.23783009, 0.51129049, 0.45445835, 0.9633773 ],
       [0.35141132, 0.76921435, 0.82903287, 0.28581615, 0.54239443,
        0.86824723, 0.7153195 , 0.94427109, 0.23941906, 0.91052718],
       [0.29125396, 0.06753758, 0.45121139, 0.86504823, 0.08892404,
        0.49619088, 0.54075155, 0.97568856, 0.62801721, 0.8242723 ],
       [0.40800418, 0.57823103, 0.3283284